import Head from 'next/head'
import Image from 'next/image'
import { auth } from '../app/firebaseApp';
import { useRouter } from 'next/router';
import { useAuthState } from 'react-firebase-hooks/auth';
import Header from '../components/Header';

export default function Home() {

  const [user] = useAuthState(auth);
  const router = useRouter();

  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main>
        { false &&
          <div >
            <div>
              <h1>
              Hello {auth.currentUser.email}.
                <a onClick={() => {
                  auth.signOut();
                  router.push('/login');
                  }}>Sign-out</a>
              </h1>
            </div>
            <div>
              <img src={auth.currentUser.photoURL} alt={auth.currentUser.displayName}/>
            </div>
          </div>
        }
      </main>
    </div>
  )
}
